FROM node:14.19.1-alpine

# Install dependencies
RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python3 python3-dev py3-pip yaml-dev git bash

RUN pip3 install --global-option="--with-libyaml" --force pyyaml && \
    pip3 install grow

WORKDIR /usr/src/app
