version: "3.7"
services:
  amp.dev:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
      - "8083:8083"
    volumes:
      - ./:/usr/src/app

