name: AMP.DEV DEV CI

on:
  push:
    branches: [ ci-pipeline ]
  pull_request_target:
    types:
      - closed
    branches:    
      - 'ci-pipeline'


jobs:

  set_build_branch:
    runs-on: ubuntu-latest

    steps:
      
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BUILD_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        id: extract_branch
      
      - name: Print branch name
        run: echo "${{ env.BUILD_BRANCH }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push AMP.DEV Docker Image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          tags: div1114/amp-dev:${{ env.BUILD_BRANCH }}
          build-args: |
            "AMP_DOC_TOKEN=${{ secrets.AMP_DOC_TOKEN }}"
          push: true 


   